-- Pokemon Crystal Address Relocations
-- Generated by Complete ROM Comparison Tool

local addresses = {
    -- Analysis confidence: 75%
    -- ROM type: unknown

    player_name = {
        vanilla = 0xD47D,
        patched = 0x7F8D,
        name = "Player Name",
        confidence = 0.95
    },
    pokedex_caught = {
        vanilla = 0xDE99,
        patched = 0xC912,
        name = "Pokedex Caught Flags",
        confidence = 0.95
    },
    pokedex_seen = {
        vanilla = 0xDEB9,
        patched = 0xD26D,
        name = "Pokedex Seen Flags",
        confidence = 0.95
    },
    party_data = {
        vanilla = 0xDCDF,
        patched = 0x3801,
        name = "Party Pokemon Data",
        confidence = 0.95
    },
    player_id = {
        vanilla = 0xD47B,
        patched = 0x20BE,
        name = "Player Trainer ID",
        confidence = 0.95
    },
    party_count = {
        vanilla = 0xDCD7,
        patched = 0x4,
        name = "Party Pokemon Count",
        confidence = 0.95
    },
    party_species = {
        vanilla = 0xDCD8,
        patched = 0x5B21,
        name = "Party Species List",
        confidence = 0.95
    },
    current_box = {
        vanilla = 0xD8BC,
        patched = 0x3E2B,
        name = "Current PC Box",
        confidence = 0.95
    },
    badges_kanto = {
        vanilla = 0xD57D,
        patched = 0xD53D,
        name = "Kanto Badges",
        confidence = 0.7
    },
}

return addresses